name: audit

on:
  schedule:
    - cron: '0 13 * * 1' # Every Monday at 1PM UTC (6AM PST)

permissions:
  contents: read

jobs:
  audit:
    if: github.repository == 'dan-livingston/vite-library-template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm audit --production
